### ISSUE TITLE
Keyframe selection

### ISSUE THREAD

**Issue by DornAres** [versatran01/dsol#6]
Hey, nice work!
After glancing over your paper, I thought about optimizing my LDSO fork with your DSO changes for a better framerate. 
Apparently, the keyframe creation process seems to be the most time-consuming, so that would be one change I'd like to try out. 
I know where the keyframe selection is in LDSO, but could you point me towards the right code section in your repo so that I could easily implement it in my repo? Thanks a lot!

**Comment by versatran01** [comment]
Just to quickly explain what I meant in the paper: keyframe creation is time-consuming because it needs to run PBA. DSO likes to create many keyframes and remove some during marginalization (it allows marginalizing more than one keyframes). Whether that's good or not depends on the rest of the implementation. DSO limits the max number of points to 2000, so maybe it's ok for it to keep creating keyframes. In my implementation, I do not put a limit on the number of points, so I want to avoid creating too many keyframes. Therefore, if you have a dso fork, then this strategy may not be for you. Also, you can easily set some parameters in DSO to control how frequently a keyframe gets added.

That being said, here is the code section.
https://github.com/versatran01/dsol/blob/009445f98ad09a47370609efa6614a39453a54b9/sv/dsol/odom.cpp#L334

**Comment by DornAres** [comment]
Ah I see, thanks for explaining!
